# Generated by Django 5.1.1 on 2024-12-13 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='std_id',
            field=models.CharField(blank=True, max_length=10, unique=True),
        ),
    ]
