# Generated by Django 5.1.1 on 2024-12-14 19:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_libraryreview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libraryreview',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='library_reviews', to=settings.AUTH_USER_MODEL),
        ),
    ]
