# Generated by Django 5.1.1 on 2024-12-14 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_alter_libraryreview_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='libraryreview',
            name='user',
        ),
    ]
